#ifndef TOKEN_H
#define TOKEN_H

#include <stddef.h>

typedef enum tok_type{
    EXCLAMATION_TOKEN_TYPE,
    QUESTION_MARK_TOKEN_TYPE,

    PLUS_TOKEN_TYPE, MINUS_TOKEN_TYPE,
	SLASH_TOKEN_TYPE, ASTERISK_TOKEN_TYPE,
	COMMA_TOKEN_TYPE, DOT_TOKEN_TYPE,
    DOUBLE_DOT_TOKEN_TYPE,
    DOUBLE_ASTERISK_TOKEN_TYPE,

    LESS_TOKEN_TYPE, GREATER_TOKEN_TYPE,
    LESS_EQUALS_TOKEN_TYPE, GREATER_EQUALS_TOKEN_TYPE,
    EQUALS_EQUALS_TOKEN_TYPE, NOT_EQUALS_TOKEN_TYPE,

    OR_TOKEN_TYPE, AND_TOKEN_TYPE,

    LEFT_SQUARE_TOKEN_TYPE, RIGHT_SQUARE_TOKEN_TYPE,
    LEFT_PAREN_TOKEN_TYPE, RIGHT_PAREN_TOKEN_TYPE,
    LEFT_BRACKET_TOKEN_TYPE, RIGHT_BRACKET_TOKEN_TYPE,

    EQUALS_TOKEN_TYPE, COMPOUND_ADD_TOKEN_TYPE,
	COMPOUND_SUB_TOKEN_TYPE, COMPOUND_MUL_TOKEN_TYPE,
	COMPOUND_DIV_TOKEN_TYPE, COLON_TOKEN_TYPE,
	SEMICOLON_TOKEN_TYPE,

    NOT_BITWISE_TOKEN_TYPE, LEFT_SHIFT_TOKEN_TYPE,
    RIGHT_SHIFT_TOKEN_TYPE, AND_BITWISE_TOKEN_TYPE,
    XOR_BITWISE_TOKEN_TYPE, OR_BITWISE_TOKEN_TYPE,

    // keywords
	MOD_TOKEN_TYPE, EMPTY_TOKEN_TYPE,
    FALSE_TOKEN_TYPE, TRUE_TOKEN_TYPE,
    LET_TOKEN_TYPE, MUT_TOKEN_TYPE,
    IF_TOKEN_TYPE, ELIF_TOKEN_TYPE, ELSE_TOKEN_TYPE,
    WHILE_TOKEN_TYPE, FOR_TOKEN_TYPE,
    STOP_TOKEN_TYPE, CONTINUE_TOKEN_TYPE,
    ARRAY_TOKEN_TYPE, LIST_TOKEN_TYPE,
    TO_TOKEN_TYPE, DICT_TOKEN_TYPE,
    RECORD_TOKEN_TYPE, PROC_TOKEN_TYPE,
    ANON_TOKEN_TYPE, RET_TOKEN_TYPE,
    IMPORT_TOKEN_TYPE, AS_TOKEN_TYPE,
    BOOL_TOKEN_TYPE, FLOAT_TOKEN_TYPE,
    INT_TOKEN_TYPE, STR_TOKEN_TYPE,
    IS_TOKEN_TYPE, TRY_TOKEN_TYPE,
    CATCH_TOKEN_TYPE, THROW_TOKEN_TYPE,
    EXPORT_TOKEN_TYPE,

    //types
    INT_TYPE_TOKEN_TYPE, FLOAT_TYPE_TOKEN_TYPE,
    STR_TYPE_TOKEN_TYPE, TEMPLATE_TYPE_TOKEN_TYPE,

    IDENTIFIER_TOKEN_TYPE,
    EOF_TOKEN_TYPE
}TokType;

typedef struct token{
    int        line;
    TokType    type;
    size_t     lexeme_len;
    char       *lexeme;
    size_t     literal_size;
	void       *literal;
    const char *pathname;
    void       *extra;
}Token;

typedef enum template_item_type{
    STR_TEMPLATE_ITEM_TYPE,
    TOKENS_TEMPLATE_ITEM_TYPE,
}TemplateItemType;

typedef struct template_item{
    TemplateItemType type;
    void             *value;
}TemplateItem;

#endif
